
#define MAINPREFIX z
#define PREFIX vigilia

#include "script_version.hpp"

#define VERSION MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD

#define REQUIREDVERSION 2.08
#define REQUIRED_CBA_VERSION {3,15,7}
#define REQUIRED_ACE_VERSION {3,15,0}

#ifdef COMPONENT_BEAUTIFIED
  #define COMPONENT_NAME QUOTE(Vigilia - COMPONENT_BEAUTIFIED)
#else
  #define COMPONENT_NAME QUOTE(Vigilia - COMPONENT)
#endif
