#define COMPONENT jammer
#define COMPONENT_BEAUTIFIED Jammer


#define IED_JAMMING_MIN_DISTANCE 50
#define IED_JAMMING_MAX_DISTANCE 500
#define IED_JAMMING_DEFAULT_DISTANCE 150
#define RADIO_TOTAL_JAMMING_MIN_DISTANCE 500
#define RADIO_TOTAL_JAMMING_MAX_DISTANCE 10000
#define RADIO_TOTAL_JAMMING_DEFAULT_DISTANCE 2500
#define RADIO_PARTIAL_JAMMING_MIN_DISTANCE 500
#define RADIO_PARTIAL_JAMMING_MAX_DISTANCE 15000
#define RADIO_PARTIAL_JAMMING_DEFAULT_DISTANCE 5000
#define TRAILING_DECIMALS 0
#define IS_SERVER_SETTINGS 1

#include "\z\vigilia\addons\main\script_mod.hpp"

#ifdef DEBUG_ENABLED_JAMMER
    #define DEBUG_MODE_FULL
#endif

#ifdef DEBUG_SETTINGS_JAMMER
    #define DEBUG_SETTINGS DEBUG_SETTINGS_JAMMER
#endif

#include "\z\vigilia\addons\main\script_macros.hpp"
